version: '2'

services:

  db:
    build: .
    command: postgres -c config_file=postgresql.conf
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: goat-trex
      POSTGRES_DB: zoo
    ports:
      - 192.168.101.22:3432:5432
    volumes:
      - ./data:/var/lib/postgresql/data

